global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # Changed from localhost

  # MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql_exporter:9104']
    scrape_interval: 10s
    metrics_path: /metrics
    relabel_configs:
      - target_label: instance
        replacement: 'mysql_server'  # Set same instance name

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - target_label: instance
        replacement: 'mysql_server'  # Same instance name

  # Application metrics (if your app exposes metrics)
  - job_name: 'memo_app'
    static_configs:
      - targets: ['memo_app:3000']
    scrape_interval: 15s
    metrics_path: /metrics