apiVersion: 1

datasources:
  # REMOVED THE DUPLICATE PROMETHEUS - It's already in prometheus.yml
  
  - name: MySQL-MemoSystem
    type: mysql
    access: proxy
    url: mysql:3306
    database: memo_system
    user: memo_user
    secureJsonData:
      password: memo_pass
    isDefault: false
    jsonData:
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      timezone: "UTC"
    editable: true